# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets  # type: ignore


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 389)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 60, 321, 21))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 150, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 200, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 260, 81, 16))
        self.label_4.setObjectName("label_4")
        self.btn_procesar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_procesar.setGeometry(QtCore.QRect(330, 220, 75, 24))
        self.btn_procesar.setObjectName("btn_procesar")
        self.operaciones_cb = QtWidgets.QComboBox(parent=self.centralwidget)
        self.operaciones_cb.setGeometry(QtCore.QRect(310, 160, 121, 22))
        self.operaciones_cb.setObjectName("operaciones_cb")
        self.operaciones_cb.addItem("")
        self.operaciones_cb.addItem("")
        self.operaciones_cb.addItem("")
        self.operaciones_cb.addItem("")
        self.operaciones_cb.addItem("")
        self.operaciones_cb.addItem("")
        self.numero1 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.numero1.setGeometry(QtCore.QRect(130, 140, 141, 31))
        self.numero1.setObjectName("numero1")
        self.numero2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.numero2.setGeometry(QtCore.QRect(130, 190, 141, 31))
        self.numero2.setObjectName("numero2")
        self.resultado = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.resultado.setGeometry(QtCore.QRect(130, 250, 141, 31))
        self.resultado.setObjectName("resultado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate(
            "MainWindow", "Mi Primer Programa en QT"))
        self.label_2.setText(_translate("MainWindow", "Numero 1"))
        self.label_3.setText(_translate("MainWindow", "Numero 2"))
        self.label_4.setText(_translate("MainWindow", "Resultado"))
        self.btn_procesar.setText(_translate("MainWindow", "Procesar"))
        self.operaciones_cb.setItemText(0, _translate("MainWindow", "suma"))
        self.operaciones_cb.setItemText(1, _translate("MainWindow", "resta"))
        self.operaciones_cb.setItemText(
            2, _translate("MainWindow", "multiplicacion"))
        self.operaciones_cb.setItemText(
            3, _translate("MainWindow", "division"))
        self.operaciones_cb.setItemText(
            4, _translate("MainWindow", "potenciacion"))
        self.operaciones_cb.setItemText(
            5, _translate("MainWindow", "radicacion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
