# Form implementation generated from reading ui file 'clientes_registrados.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(722, 532)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(0, 20, 721, 81))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(36)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 100, 721, 31))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.table_historial = QtWidgets.QTableWidget(parent=Form)
        self.table_historial.setGeometry(QtCore.QRect(10, 180, 701, 271))
        self.table_historial.setObjectName("table_historial")
        self.table_historial.setColumnCount(3)
        self.table_historial.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        item.setFont(font)
        self.table_historial.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        item.setFont(font)
        self.table_historial.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        item.setFont(font)
        self.table_historial.setHorizontalHeaderItem(2, item)
        self.btn_regresar = QtWidgets.QPushButton(parent=Form)
        self.btn_regresar.setGeometry(QtCore.QRect(10, 140, 75, 24))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        self.btn_regresar.setFont(font)
        self.btn_regresar.setObjectName("btn_regresar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "ROARI HOTEL"))
        self.label.setText(_translate("Form", "Clientes Registrados"))
        item = self.table_historial.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.table_historial.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre Completo"))
        item = self.table_historial.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Celular"))
        self.btn_regresar.setText(_translate("Form", "Regresar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
