# Form implementation generated from reading ui file 'views/ui/ventana_principal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget
from controllers.ventana_principal_controller import Ventana_Principal_Controller


class Ui_Form_Ventana_Principal(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(722, 532)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 361, 531))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("views/ui\\../../resources/images/hotel_imagen.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(420, 80, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(30)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_reservar = QtWidgets.QPushButton(parent=Form)
        self.btn_reservar.setGeometry(QtCore.QRect(550, 180, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(9)
        font.setItalic(False)
        self.btn_reservar.setFont(font)
        self.btn_reservar.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("views/ui\\../../resources/images/icons/reservacion.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_reservar.setIcon(icon)
        self.btn_reservar.setIconSize(QtCore.QSize(50, 50))
        self.btn_reservar.setObjectName("btn_reservar")
        self.btn_habitaciones = QtWidgets.QPushButton(parent=Form)
        self.btn_habitaciones.setGeometry(QtCore.QRect(450, 360, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        self.btn_habitaciones.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("views/ui\\../../resources/images/icons/habitacion.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_habitaciones.setIcon(icon1)
        self.btn_habitaciones.setIconSize(QtCore.QSize(50, 50))
        self.btn_habitaciones.setObjectName("btn_habitaciones")
        self.btn_clientes = QtWidgets.QPushButton(parent=Form)
        self.btn_clientes.setGeometry(QtCore.QRect(550, 270, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        self.btn_clientes.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("views/ui\\../../resources/images/icons/cliente.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_clientes.setIcon(icon2)
        self.btn_clientes.setIconSize(QtCore.QSize(50, 50))
        self.btn_clientes.setObjectName("btn_clientes")
        self.btn_historial = QtWidgets.QPushButton(parent=Form)
        self.btn_historial.setGeometry(QtCore.QRect(380, 270, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        self.btn_historial.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("views/ui\\../../resources/images/icons/historial.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_historial.setIcon(icon3)
        self.btn_historial.setIconSize(QtCore.QSize(50, 50))
        self.btn_historial.setObjectName("btn_historial")
        self.btn_servicio = QtWidgets.QPushButton(parent=Form)
        self.btn_servicio.setGeometry(QtCore.QRect(380, 180, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        self.btn_servicio.setFont(font)
        self.btn_servicio.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("views/ui\\../../resources/images/icons/servicio.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_servicio.setIcon(icon4)
        self.btn_servicio.setIconSize(QtCore.QSize(50, 50))
        self.btn_servicio.setObjectName("btn_servicio")
        self.btn_salir = QtWidgets.QPushButton(parent=Form)
        self.btn_salir.setGeometry(QtCore.QRect(640, 480, 75, 31))
        self.btn_salir.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("views/ui\\../../resources/images/icons/flecha_atras.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_salir.setIcon(icon5)
        self.btn_salir.setIconSize(QtCore.QSize(50, 50))
        self.btn_salir.setFlat(True)
        self.btn_salir.setObjectName("btn_salir")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "ROARI HOTEL"))
        self.btn_reservar.setText(_translate("Form", "     Reservar\n"
"     Habitación"))
        self.btn_habitaciones.setText(_translate("Form", "  Habitaciones \n"
"  Disponibles"))
        self.btn_clientes.setText(_translate("Form", "  Clientes \n"
"  Registrados"))
        self.btn_historial.setText(_translate("Form", "   Historial \n"
"   de Reservas"))
        self.btn_servicio.setText(_translate("Form", " Servicio\n"
" a la Habitación"))

class Form_Ventana_Principal(QWidget, Ui_Form_Ventana_Principal):
    def __init__(self):
        super().__init__()
        self.setupUi(self)  # Configura la UI generada

        self.ventana_principal_controller = Ventana_Principal_Controller(self)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_Ventana_Principal()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
