# Form implementation generated from reading ui file 'views/ui/reservar_habitacion.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_Reservar_Habitacion(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Link, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Link, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Link, brush
        )
        Form.setPalette(palette)
        Form.setStyleSheet("QWidget{\n    background-color: rgb(242, 242, 242);\n}")
        self.txt_nombre_cliente = QtWidgets.QLineEdit(parent=Form)
        self.txt_nombre_cliente.setGeometry(QtCore.QRect(60, 180, 291, 31))
        self.txt_nombre_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_nombre_cliente.setFrame(False)
        self.txt_nombre_cliente.setObjectName("txt_nombre_cliente")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(60, 160, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(60, 240, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(60, 320, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(60, 400, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.txt_celular = QtWidgets.QLineEdit(parent=Form)
        self.txt_celular.setGeometry(QtCore.QRect(60, 260, 291, 31))
        self.txt_celular.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_celular.setFrame(False)
        self.txt_celular.setObjectName("txt_celular")
        self.txt_fecha_ingreso = QtWidgets.QLineEdit(parent=Form)
        self.txt_fecha_ingreso.setGeometry(QtCore.QRect(60, 350, 291, 31))
        self.txt_fecha_ingreso.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_fecha_ingreso.setFrame(False)
        self.txt_fecha_ingreso.setObjectName("txt_fecha_ingreso")
        self.txt_fecha_salida = QtWidgets.QLineEdit(parent=Form)
        self.txt_fecha_salida.setGeometry(QtCore.QRect(60, 420, 291, 31))
        self.txt_fecha_salida.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_fecha_salida.setFrame(False)
        self.txt_fecha_salida.setObjectName("txt_fecha_salida")
        self.box_tipo_habitacion = QtWidgets.QComboBox(parent=Form)
        self.box_tipo_habitacion.setGeometry(QtCore.QRect(450, 180, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.box_tipo_habitacion.setFont(font)
        self.box_tipo_habitacion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.box_tipo_habitacion.setFrame(True)
        self.box_tipo_habitacion.setObjectName("box_tipo_habitacion")
        self.box_tipo_habitacion.addItem("")
        self.box_tipo_habitacion.addItem("")
        self.box_tipo_habitacion.addItem("")
        self.box_tipo_habitacion.addItem("")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(450, 160, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(450, 240, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(450, 320, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.box_estado_reservacion = QtWidgets.QComboBox(parent=Form)
        self.box_estado_reservacion.setGeometry(QtCore.QRect(450, 340, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.box_estado_reservacion.setFont(font)
        self.box_estado_reservacion.setStyleSheet(
            "background-color: rgb(255, 255, 255);"
        )
        self.box_estado_reservacion.setFrame(True)
        self.box_estado_reservacion.setObjectName("box_estado_reservacion")
        self.box_estado_reservacion.addItem("")
        self.box_estado_reservacion.addItem("")
        self.box_estado_reservacion.addItem("")
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setGeometry(QtCore.QRect(450, 400, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.txt_total_pago = QtWidgets.QLineEdit(parent=Form)
        self.txt_total_pago.setGeometry(QtCore.QRect(450, 420, 291, 31))
        self.txt_total_pago.setStyleSheet("background: transparent;")
        self.txt_total_pago.setFrame(False)
        self.txt_total_pago.setObjectName("txt_total_pago")
        self.btn_guardar = QtWidgets.QPushButton(parent=Form)
        self.btn_guardar.setGeometry(QtCore.QRect(480, 500, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.btn_guardar.setFont(font)
        self.btn_guardar.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #EC4424; /* Rojo */\n"
            "    color: #FFFFFF; /* Texto blanco */\n"
            "    border-radius: 8px; /* Bordes redondeados opcionales */\n"
            "    font-weight: bold; /* Negrita opcional */\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #FF5733; /* Rojo más claro en hover */\n"
            "}"
        )
        self.btn_guardar.setObjectName("btn_guardar")
        self.btn_cancelar = QtWidgets.QPushButton(parent=Form)
        self.btn_cancelar.setGeometry(QtCore.QRect(610, 500, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.btn_cancelar.setFont(font)
        self.btn_cancelar.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #A9A9A9; /* Gris medio */\n"
            "    color: #FFFFFF; /* Texto blanco */\n"
            "    border-radius: 8px; /* Bordes redondeados opcionales */\n"
            "    font-weight: bold;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #808080; /* Gris oscuro en hover */\n"
            "}"
        )
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.label_11 = QtWidgets.QLabel(parent=Form)
        self.label_11.setGeometry(QtCore.QRect(0, -10, 801, 141))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(20)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setMouseTracking(False)
        self.label_11.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0.514, y1:0.0343182, x2:0.500554, y2:0.727, stop:0 rgba(242, 242, 242, 255), stop:1 rgba(255, 255, 255, 255));"
        )
        self.label_11.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignBottom | QtCore.Qt.AlignmentFlag.AlignHCenter
        )
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=Form)
        self.label_12.setGeometry(QtCore.QRect(350, 10, 91, 91))
        self.label_12.setText("")
        self.label_12.setPixmap(
            QtGui.QPixmap("views/ui\\../../resources/images/logo.jpg")
        )
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.box_numero_habitacion = QtWidgets.QComboBox(parent=Form)
        self.box_numero_habitacion.setGeometry(QtCore.QRect(450, 260, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.box_numero_habitacion.setFont(font)
        self.box_numero_habitacion.setStyleSheet(
            "background-color: rgb(255, 255, 255);"
        )
        self.box_numero_habitacion.setFrame(True)
        self.box_numero_habitacion.setObjectName("box_numero_habitacion")
        self.box_numero_habitacion.addItem("")
        self.box_numero_habitacion.addItem("")
        self.box_numero_habitacion.addItem("")
        self.box_numero_habitacion.addItem("")
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setGeometry(QtCore.QRect(60, 200, 291, 16))
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setStyleSheet("background: transparent;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(parent=Form)
        self.frame_3.setGeometry(QtCore.QRect(60, 280, 291, 16))
        self.frame_3.setAutoFillBackground(False)
        self.frame_3.setStyleSheet("background: transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(parent=Form)
        self.frame_4.setGeometry(QtCore.QRect(60, 370, 291, 16))
        self.frame_4.setAutoFillBackground(False)
        self.frame_4.setStyleSheet("background: transparent;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_4.setLineWidth(1)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(parent=Form)
        self.frame_5.setGeometry(QtCore.QRect(60, 440, 291, 16))
        self.frame_5.setAutoFillBackground(False)
        self.frame_5.setStyleSheet("background: transparent;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_5.setLineWidth(1)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(parent=Form)
        self.frame_6.setGeometry(QtCore.QRect(450, 440, 291, 16))
        self.frame_6.setAutoFillBackground(False)
        self.frame_6.setStyleSheet("background: transparent;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_6.setLineWidth(1)
        self.frame_6.setObjectName("frame_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Nombre de Cliente"))
        self.label_4.setText(_translate("Form", "Celular"))
        self.label_5.setText(_translate("Form", "Fecha de Ingreso"))
        self.label_6.setText(_translate("Form", "Fecha de Salida"))
        self.box_tipo_habitacion.setItemText(0, _translate("Form", "Simple"))
        self.box_tipo_habitacion.setItemText(1, _translate("Form", "Doble"))
        self.box_tipo_habitacion.setItemText(2, _translate("Form", "Matrimonial"))
        self.box_tipo_habitacion.setItemText(3, _translate("Form", "Suite"))
        self.label_7.setText(_translate("Form", "Tipo de Habitación"))
        self.label_8.setText(_translate("Form", "Número de Habitación"))
        self.label_9.setText(_translate("Form", "Estado de la Reservación"))
        self.box_estado_reservacion.setItemText(0, _translate("Form", "Pagada"))
        self.box_estado_reservacion.setItemText(1, _translate("Form", "Cancelada"))
        self.box_estado_reservacion.setItemText(2, _translate("Form", "Pendiente"))
        self.label_10.setText(_translate("Form", "Total a Pagar"))
        self.btn_guardar.setText(_translate("Form", "Guardar"))
        self.btn_cancelar.setText(_translate("Form", "Cancelar"))
        self.label_11.setText(_translate("Form", "Reservar Habitación"))
        self.box_numero_habitacion.setItemText(0, _translate("Form", "2"))
        self.box_numero_habitacion.setItemText(1, _translate("Form", "3"))
        self.box_numero_habitacion.setItemText(2, _translate("Form", "4"))
        self.box_numero_habitacion.setItemText(3, _translate("Form", "7"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_Reservar_Habitacion()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
